kind: pipeline
name: default

#steps:
#- name: test
# image: node
#commands:
#- npm install
#- npm run test
steps:
- name: publish-to-docker
  image: plugins/docker
  settings:
    repo: jackharrhy/manriquebot
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push
      - tag
